//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Beg_Word
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Beg_Word()
    {
        this.Beg_WordFiles = new HashSet<Beg_WordFiles>();
        this.Beg_WordTranslate = new HashSet<Beg_WordTranslate>();
        this.Beg_WordTest = new HashSet<Beg_WordTest>();
        this.Beg_WordUserTest = new HashSet<Beg_WordUserTest>();
    }

    public int Id { get; set; }
    public string Word { get; set; }
    public string Explain { get; set; }
    public Nullable<int> SortOrder { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Beg_WordFiles> Beg_WordFiles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Beg_WordTranslate> Beg_WordTranslate { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Beg_WordTest> Beg_WordTest { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Beg_WordUserTest> Beg_WordUserTest { get; set; }
}

public partial class Beg_WordCourse
{
    public int Id { get; set; }
    public Nullable<int> Lesson { get; set; }
    public Nullable<int> Topics { get; set; }
}

public partial class Beg_WordFiles
{
    public int Id { get; set; }
    public int BegWordId { get; set; }
    public string Name { get; set; }
    public string ContentType { get; set; }
    public byte[] Play { get; set; }

    public virtual Beg_Word Beg_Word { get; set; }
}

public partial class Beg_WordResult
{
    public int Id { get; set; }
    public string Username { get; set; }
    public string Result { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> BegWordTestId { get; set; }
    public Nullable<int> Correct { get; set; }
    public Nullable<int> wrong { get; set; }

    public virtual Beg_WordTest Beg_WordTest { get; set; }
}

public partial class Beg_WordTest
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Beg_WordTest()
    {
        this.Beg_WordResult = new HashSet<Beg_WordResult>();
    }

    public int Id { get; set; }
    public Nullable<int> BegWordId { get; set; }
    public Nullable<int> BegCourseId { get; set; }
    public string Day { get; set; }
    public Nullable<int> QuestionNumber { get; set; }
    public string Question { get; set; }
    public string Answer { get; set; }

    public virtual Beg_Word Beg_Word { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Beg_WordResult> Beg_WordResult { get; set; }
}

public partial class Beg_WordTranslate
{
    public int Id { get; set; }
    public int BegWordId { get; set; }
    public string Kannada { get; set; }
    public string KannadaDesc { get; set; }
    public string Hindi { get; set; }
    public string HindiDesc { get; set; }

    public virtual Beg_Word Beg_Word { get; set; }
}

public partial class Beg_WordUserTest
{
    public int Id { get; set; }
    public Nullable<int> BegWordId { get; set; }
    public string Username { get; set; }
    public Nullable<int> BegWordTestId { get; set; }
    public string Day { get; set; }
    public Nullable<int> QuestionNumber { get; set; }
    public string Question { get; set; }
    public string Answer { get; set; }

    public virtual Beg_Word Beg_Word { get; set; }
}
